# Chocolatey install script for codetracer-wasmi-recorder.
#
# Generated by codetracer-launcher/packaging/recorder-templates/generate.py
# from codetracer-wasmi-recorder/packaging/recorder-metadata.yml.
# DO NOT edit this file by hand — re-run the generator instead.
#
# The install flow:
#   1. Download the windows-x86_64 zip from the recorder's GitHub
#      release using the canonical CodeTracer URL convention.
#   2. Validate via sha256 — the checksum is rewritten at publish
#      time by .github/workflows/publish-chocolatey.yml.
#   3. Extract into $Env:ProgramFiles\codetracer-wasmi-recorder\ via
#      Chocolatey's Install-ChocolateyZipPackage helper, which
#      additionally registers the binary on PATH via shim creation
#      (Chocolatey shims everything in $toolsDir by default).

$ErrorActionPreference = 'Stop'

$packageName = 'codetracer-wasmi-recorder'
$toolsDir    = "$(Split-Path -Parent $MyInvocation.MyCommand.Definition)"

$url64       = 'https://github.com/metacraft-labs/codetracer-wasmi-recorder/releases/download/v0.44.0/codetracer-wasmi-recorder-0.44.0-windows-x86_64.zip'
$checksum64  = 'REPLACE_AT_PUBLISH_TIME_windows_x86_64'
$checksumType64 = 'sha256'

$packageArgs = @{
  packageName    = $packageName
  unzipLocation  = $toolsDir
  url64bit       = $url64
  checksum64     = $checksum64
  checksumType64 = $checksumType64
}

Install-ChocolateyZipPackage @packageArgs

# Chocolatey auto-shims every .exe under $toolsDir, so the
# wasmi_cli.exe binary becomes available on PATH after install
# without an explicit Install-BinFile call. If a recorder needs to
# suppress shimming for auxiliary tools, drop a `.ignore` sibling
# file next to the relevant .exe under $toolsDir.
