Name:           codetracer-wasmi-recorder
Version:        0.44.0
Release:        1%{?dist}
Summary:        CodeTracer recorder for WebAssembly modules (wasmi interpreter)

License:        MIT/Apache-2.0
URL:            https://github.com/metacraft-labs/codetracer-wasmi-recorder

# Pre-built binary path is injected at rpmbuild-time by
# packaging/rpm/build.sh through `--define "_binary_source <path>"`.
# This avoids carrying a Source0 tarball through the spec for a
# binary-only recorder package.

# Recorder runtime dependencies, materialised by generate.py from
# the per-recorder metadata's dependencies.rpm list.
Requires:       glibc
Requires:       libzstd

%description
CodeTracer recorder for WebAssembly modules (wasmi interpreter)

This package is part of the CodeTracer record/replay debugging
suite. Install the launcher (codetracer) alongside this package for
a full record/replay workflow.

%install
mkdir -p %{buildroot}/usr/bin
install -m 0755 %{_binary_source} %{buildroot}/usr/bin/wasmi_cli

%files
/usr/bin/wasmi_cli

%changelog
* Thu Jun 04 2026 Metacraft Labs <ci@metacraft-labs.com> - 0.44.0-1
- Generated by codetracer-launcher recorder-templates (M11).
