# Homebrew formula for codetracer-wasmi-recorder.
#
# Generated by codetracer-launcher/packaging/recorder-templates/generate.py
# from codetracer-wasmi-recorder/packaging/recorder-metadata.yml.
# DO NOT edit this file by hand — re-run the generator instead.
#
# Per CodeTracer Launcher §11 (M11), the per-recorder Homebrew
# formula installs the recorder binary only. The launcher (`ct`) is
# distributed separately via `brew install codetracer` from the M9
# tap.
#
# At publish time, the sha256 placeholders are rewritten by
# .github/workflows/publish-homebrew.yml using the GitHub-release
# artifacts uploaded by the recorder's release workflow.

class CodetracerWasmiRecorder < Formula
  desc "CodeTracer recorder for WebAssembly modules (wasmi interpreter)"
  homepage "https://github.com/metacraft-labs/codetracer-wasmi-recorder"
  version "0.44.0"
  license "MIT/Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/metacraft-labs/codetracer-wasmi-recorder/releases/download/v0.44.0/wasmi_cli-darwin-aarch64"
      sha256 "REPLACE_AT_PUBLISH_TIME_darwin_aarch64"
    end
    on_intel do
      url "https://github.com/metacraft-labs/codetracer-wasmi-recorder/releases/download/v0.44.0/wasmi_cli-darwin-x86_64"
      sha256 "REPLACE_AT_PUBLISH_TIME_darwin_x86_64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/metacraft-labs/codetracer-wasmi-recorder/releases/download/v0.44.0/wasmi_cli-linux-aarch64"
      sha256 "REPLACE_AT_PUBLISH_TIME_linux_aarch64"
    end
    on_intel do
      url "https://github.com/metacraft-labs/codetracer-wasmi-recorder/releases/download/v0.44.0/wasmi_cli-linux-x86_64"
      sha256 "REPLACE_AT_PUBLISH_TIME_linux_x86_64"
    end
  end

  # Source-build fallback. Each blockchain recorder uses Cargo;
  # depend on the Rust toolchain for the head path.
  head do
    url "https://github.com/metacraft-labs/codetracer-wasmi-recorder.git", branch: "main"
    depends_on "rust" => :build
  end

  depends_on "zstd"

  def install
    if build.head?
      # Source build path — cargo produces the binary at
      # target/release/wasmi_cli.
      system "cargo", "build", "--release", "--locked", "--bin", "wasmi_cli"
      bin.install "target/release/wasmi_cli" => "wasmi_cli"
    else
      # Pre-built binary path — the downloaded artifact lands as
      # `wasmi_cli-<target>`; rename to the canonical name.
      bin.install Dir["wasmi_cli*"].first => "wasmi_cli"
    end
  end

  test do
    # Smoke test: the recorder responds to --version (or --help, if
    # the recorder uses Clap's default --help convention). Asserting
    # a non-empty exit-0 output catches the "binary segfaults
    # immediately" failure mode without overconstraining the version
    # string.
    output = shell_output("#{bin}/wasmi_cli --version 2>&1", 0)
    assert_match(/wasmi_cli/, output)
  end
end
